import useEditorCanvasCtx from './useEditorCanvasCtx';
import useBottomToolbarProps from './useBottomToolbarProps';

// allow loose param typing here while we iteratively tighten hook inputs
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function useEditorAreaProps(params: any) {
  const {
    editor,
    canvasRef,
    draggingNpcId,
    setDraggingNpcId,
    draggingEventId,
    setDraggingEventId,
    tipsMinimized,
    setTipsMinimized,
    setShowHelp,
    isEnemyTabActive,
    mapWidth,
    mapHeight,
    handlePlaceActorOnMap,
    handlePlaceEventOnMap,
    mapInitialized,
    handleOpenCreateMapDialog,
    isPreparingNewMap,
    hoverCoords,
    showActiveGid,
    activeGidValue,
    npcDeletePopup,
    setNpcDeletePopup,
    handleUnplaceActorFromMap,
    npcHoverTooltip,
    uiHelpers,
    stampsState,
    hasSelection,
    selectionCount,
    handleFillSelection,
    handleDeleteSelection,
    handleClearSelection,
    leftTransitioning,
    bottomToolbarExpanded,
    setBottomToolbarNode,
    handleBottomToolbarMouseEnter,
    handleBottomToolbarMouseLeave,
    handleBottomToolbarFocus,
    handleBottomToolbarBlur,
    selectedTool,
    handleSelectTool,
    showBrushOptions,
    handleShowBrushOptions,
    handleHideBrushOptions,
    selectedBrushTool,
    setSelectedBrushTool,
    showTooltipWithDelayFn,
    hideTooltipFn,
    setShowClearLayerDialog,
    showSelectionOptions,
    handleShowSelectionOptions,
    handleHideSelectionOptions,
    selectedSelectionTool,
    setSelectedSelectionTool,
    showShapeOptions,
    handleShowShapeOptions,
    handleHideShapeOptions,
    selectedShapeTool,
    setSelectedShapeTool,
    stampMode,
    setStampMode,
    newStampName,
    setNewStampName,
    handleCreateStamp,
    stamps,
    selectedStamp,
    handleStampSelect,
    handleDeleteStamp
  } = params;

  const { ctx: editorCanvasCtx } = useEditorCanvasCtx({
    editor,
    canvasRef,
    draggingNpcId,
    setDraggingNpcId,
    draggingEventId,
    setDraggingEventId,
    tipsMinimized,
    setTipsMinimized,
    setShowHelp,
    isEnemyTabActive,
    mapWidth,
    mapHeight,
    handlePlaceActorOnMap,
    handlePlaceEventOnMap,
    mapInitialized,
    handleOpenCreateMapDialog,
    isPreparingNewMap,
    hoverCoords,
    showActiveGid,
    activeGidValue,
    hoverGidValue,
    npcDeletePopup,
    setNpcDeletePopup,
    handleUnplaceActorFromMap,
    npcHoverTooltip,
    uiHelpers,
    stampsState,
    hasSelection,
    selectionCount,
    handleFillSelection,
    handleDeleteSelection,
    handleClearSelection,
    leftTransitioning,
    bottomToolbarExpanded,
    setBottomToolbarNode,
    handleBottomToolbarMouseEnter,
    handleBottomToolbarMouseLeave,
    handleBottomToolbarFocus,
    handleBottomToolbarBlur,
    selectedTool,
    handleSelectTool,
    showBrushOptions,
    handleShowBrushOptions,
    handleHideBrushOptions,
    selectedBrushTool,
    setSelectedBrushTool,
    showTooltipWithDelayFn,
    hideTooltipFn,
    setShowClearLayerDialog,
    showSelectionOptions,
    handleShowSelectionOptions,
    handleHideSelectionOptions,
    selectedSelectionTool,
    setSelectedSelectionTool,
    showShapeOptions,
    handleShowShapeOptions,
    handleHideShapeOptions,
    selectedShapeTool,
    setSelectedShapeTool,
    stampMode,
    setStampMode,
    newStampName,
    setNewStampName,
    handleCreateStamp,
    stamps,
    selectedStamp,
    handleStampSelect,
    handleDeleteStamp
  });

  const bottomToolbarProps = useBottomToolbarProps({
    // pass through extras if provided
    ...(params.bottomToolbarPropsExtras || {})
  });

  const topBarProps = {
    toolbarExpanded: params.toolbarExpanded,
    containerRef: params.toolbarContainerRef,
    onMouseEnter: params.handleToolbarMouseEnter,
    onMouseLeave: params.handleToolbarMouseLeave,
    onFocus: params.handleToolbarFocus,
    onBlur: params.handleToolbarBlur,
    handleUndo: params.handleUndo,
    handleRedo: params.handleRedo,
    handleZoomIn: params.handleZoomIn,
    handleZoomOut: params.handleZoomOut,
    handleResetZoom: params.handleResetZoom
  };

  return { topBarProps, canvasCtx: editorCanvasCtx, bottomToolbarProps } as const;
}
