import React, { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import Tooltip from '@/components/ui/tooltip';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { User, Eye, Sword, Gift, Flag, MapPin, Volume2, HelpCircle, X, Save, Plus, Check, Rabbit, Sigma, Zap, ChevronDown, ChevronUp } from 'lucide-react';
import type { MapObject } from '@/types';
import type { LucideIcon } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Slider } from '@/components/ui/slider';
import { useDraggableResizable } from '@/hooks/useDraggableResizable';

type TabKey = 'identity' | 'visual' | 'audio' | 'stats' | 'behavior' | 'loot' | 'quest' | 'combat' | 'flags' | 'skills';

// TAB_CONFIG removed in favor of collapsible sections

interface EditEnemyWindowProps {
  open: boolean;
  onOpenChange?: (open: boolean) => void;
  enemy?: MapObject | null;
  onSave?: (obj: MapObject) => void;
  projectPath?: string;
  inline?: boolean;
  showCloseConfirm?: boolean;
  onCloseDecision?: (decision: 'save' | 'discard' | 'cancel') => void;
}

export default function EditEnemyWindow({ open, onOpenChange, enemy, onSave, projectPath = '', inline = false, showCloseConfirm = false, onCloseDecision }: EditEnemyWindowProps) {
  const { toast } = useToast();
  
  const {
    position,
    size,
    dialogRef,
    handleHeaderMouseDown,
    handleResizeMouseDown,
  } = useDraggableResizable({ id: 'edit_enemy', initialWidth: 820, initialHeight: 680, minWidth: 600, minHeight: 500 });

  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    identity: true,
    visual: false,
    audio: false,
    stats: false,
    combat: false,
    skills: false,
    behavior: false,
    loot: false,
    quest: false,
    flags: false
  });

  const toggleSection = (section: string) => {
    setExpandedSections(prev => ({ ...prev, [section]: !prev[section] }));
  };
  const [name, setName] = useState(() => enemy?.name || '');
  const [level, setLevel] = useState<number>(() => enemy?.level ?? 1);
  const [rarity, setRarity] = useState<'common'|'uncommon'|'rare'|'unique'>(() => (enemy?.properties?.rarity as 'common'|'uncommon'|'rare'|'unique') || 'common');
  const [count, setCount] = useState<number>(() => enemy?.number ?? 1);
  const [category, setCategory] = useState(() => enemy?.category || '');
  const [include, setInclude] = useState<string>(() => enemy?.properties?.include || '');
  const [isHumanoid, setIsHumanoid] = useState<boolean>(() => (enemy?.properties?.humanoid === 'true'));
  const [isLifeform, setIsLifeform] = useState<boolean>(() => (enemy?.properties?.lifeform === 'false' ? false : true));
  const [isAddingCategory, setIsAddingCategory] = useState(false);
  const [newCatInput, setNewCatInput] = useState('');
  const [presets, setPresets] = useState<string[]>([]);
  const [isLoadingPresets, setIsLoadingPresets] = useState(false);

  useEffect(() => {
    const fetchPresets = async () => {
      if (open && projectPath && window.electronAPI?.listEnemies) {
        setIsLoadingPresets(true);
        try {
          const list = await window.electronAPI.listEnemies(projectPath);
          setPresets(list);
        } catch (e) {
          console.error('Failed to fetch presets:', e);
        } finally {
          setIsLoadingPresets(false);
        }
      }
    };
    fetchPresets();
  }, [open, projectPath]);

  const handleSaveAsPreset = async () => {
    if (!projectPath || !window.electronAPI?.saveEnemyPreset) return;
    if (!name.trim()) return;

    const sanitizeFileName = (input: string) =>
      String(input || '')
        .toLowerCase()
        .replace(/[<>:"/\\|?*]/g, '_')
        .trim()
        .replace(/\s+/g, '_')
        .replace(/_{2,}/g, '_') || 'unnamed_enemy';

    const sanitizedName = sanitizeFileName(name);
    const filename = `${sanitizedName}.txt`;

    const lines: string[] = [];
    lines.push(`# Enemy file generated by Flare Studio`);
    if (include) lines.push(`INCLUDE ${include}`);
    lines.push(`name=${name}`);
    
    if (category) {
      // Categories should be comma separated lists.
      lines.push(`categories=${category}`);
    }

    if (level !== undefined && level !== null) lines.push(`level=${level}`);
    if (rarity) lines.push(`rarity=${rarity}`);
    if (xp) lines.push(`xp=${xp}`);
    if (gold) lines.push(`gold=${gold}`);
    
    // Core Stats (Standard key=value)
    if (speed) lines.push(`speed=${speed}`);
    if (cooldown) lines.push(`cooldown=${cooldown}`);
    if (turnDelay) lines.push(`turn_delay=${turnDelay}`);
    if (wanderRadius) lines.push(`wander_radius=${wanderRadius}`);
    if (waypoints) lines.push(`waypoints=${waypoints}`);
    if (waypointPause) lines.push(`waypoint_pause=${waypointPause}`);
    
    // Core Stats (stat=id,value)
    if (hp) lines.push(`stat=hp,${hp}`);
    if (mp) lines.push(`stat=mp,${mp}`);
    if (accuracy) lines.push(`stat=accuracy,${accuracy}`);
    if (avoidance) lines.push(`stat=avoidance,${avoidance}`);
    if (crit) lines.push(`stat=crit,${crit}`);
    if (poise) lines.push(`stat=poise,${poise}`);
    if (stealth) lines.push(`stat=stealth,${stealth}`);
    if (absorbMin) lines.push(`stat=absorb_min,${absorbMin}`);
    if (absorbMax) lines.push(`stat=absorb_max,${absorbMax}`);
    
    // Damage stats
    if (dmgMeleeMin) lines.push(`stat=dmg_melee_min,${dmgMeleeMin}`);
    if (dmgMeleeMax) lines.push(`stat=dmg_melee_max,${dmgMeleeMax}`);
    if (dmgRangedMin) lines.push(`stat=dmg_ranged_min,${dmgRangedMin}`);
    if (dmgRangedMax) lines.push(`stat=dmg_ranged_max,${dmgRangedMax}`);

    // Utility stats
    if (reflectChance) lines.push(`stat=reflect_chance,${reflectChance}`);
    if (returnDamage) lines.push(`stat=return_damage,${returnDamage}`);
    if (currencyFind) lines.push(`stat=currency_find,${currencyFind}`);
    if (itemFind) lines.push(`stat=item_find,${itemFind}`);

    // Ranges & Behavior
    if (meleeRange) lines.push(`melee_range=${meleeRange}`);
    if (threatRange) lines.push(`threat_range=${threatRange}`);
    if (fleeRange) lines.push(`flee_range=${fleeRange}`);
    if (fleeDuration) lines.push(`flee_duration=${fleeDuration}`);
    if (fleeCooldown) lines.push(`flee_cooldown=${fleeCooldown}`);
    if (chancePursue) lines.push(`chance_pursue=${chancePursue}`);
    if (chanceFlee) lines.push(`chance_flee=${chanceFlee}`);
    if (combatStyle) lines.push(`combat_style=${combatStyle}`);

    // Flags
    if (isFacing) lines.push(`facing=true`);
    if (isFlying) lines.push(`flying=true`);
    if (isIntangible) lines.push(`intangible=true`);
    if (isHumanoid) lines.push(`humanoid=true`);
    if (!isLifeform) lines.push(`lifeform=false`);
    
    // Visuals & Audio
    if (gfx) lines.push(`gfx=${gfx}`);
    if (animations) lines.push(`animations=${animations}`);
    if (renderLayers) lines.push(`render_layers=${renderLayers}`);
    if (animationSlots) lines.push(`animation_slots=${animationSlots}`);
    
    // Powers
    // Flare formats power as: power=state,power_id,chance
    if (powers && Array.isArray(powers)) {
       powers.forEach((p: any) => {
         if (p.id) lines.push(`power=${p.state || 'melee'},${p.id},${p.chance || 100}`);
       });
    }

    if (passivePowers) lines.push(`passive_powers=${passivePowers}`);
    if (cooldownHit) lines.push(`cooldown_hit=${cooldownHit}`);
    if (powerFilter) lines.push(`power_filter=${powerFilter}`);
    if (script) lines.push(`script=${script}`);

    // Loot
    if (loot) lines.push(`loot=${loot}`);
    if (lootCount) lines.push(`loot_count=${lootCount}`);
    if (firstDefeatLoot) lines.push(`first_defeat_loot=${firstDefeatLoot}`);
    if (questLoot) lines.push(`quest_loot=${questLoot}`);
    if (defeatStatus) lines.push(`defeat_status=${defeatStatus}`);

    const customLines = (customPropsRaw || '').split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
    lines.push(...customLines);

    const content = lines.join('\n') + '\n';

    try {
      const success = await window.electronAPI.saveEnemyPreset(projectPath, filename, content);
      if (success) {
        const list = await window.electronAPI.listEnemies(projectPath);
        setPresets(list);
        setInclude(`enemies/${filename}`);
        toast({
          title: 'Enemy file saved',
          description: `Enemy saved to enemies/${filename}`,
          variant: 'default',
        });
      }
    } catch (e) {
      console.error('Failed to save enemy file:', e);
    }
  };

  const selectedCategories = category.split(',').map(s => s.trim()).filter(Boolean);

  const toggleCategory = (cat: string) => {
    if (selectedCategories.includes(cat)) {
      setCategory(selectedCategories.filter(c => c !== cat).join(','));
    } else {
      setCategory([...selectedCategories, cat].join(','));
    }
  };

  const addCategory = () => {
    const trimmed = newCatInput.trim();
    if (trimmed && !selectedCategories.includes(trimmed)) {
      setCategory([...selectedCategories, trimmed].join(','));
    }
    setNewCatInput('');
    setIsAddingCategory(false);
  };

  // Visual
  const [tilesetPath, setTilesetPath] = useState<string>(() => (enemy?.properties?.tilesetPath as string) || '');
  const [portraitPath, setPortraitPath] = useState<string>(() => (enemy?.properties?.portraitPath as string) || '');
  const [gfx, setGfx] = useState<string>(() => (enemy?.properties?.gfx as string) || '');
  const [renderLayers, setRenderLayers] = useState<string>(() => enemy?.properties?.render_layers || '');
  const [animationSlots, setAnimationSlots] = useState<string>(() => enemy?.properties?.animation_slots || '');
  const [suppressHp, setSuppressHp] = useState<boolean>(() => (enemy?.properties?.suppress_hp === 'true'));

  // Audio
  const [sfxAttack, setSfxAttack] = useState<string>(() => enemy?.properties?.sfx_attack || '');
  const [sfxHit, setSfxHit] = useState<string>(() => enemy?.properties?.sfx_hit || '');
  const [sfxDie, setSfxDie] = useState<string>(() => enemy?.properties?.sfx_die || '');
  const [sfxCritDie, setSfxCritDie] = useState<string>(() => enemy?.properties?.sfx_critdie || '');

  // Stats
  const [hp, setHp] = useState<string>(() => enemy?.properties?.hp || '');
  const [mp, setMp] = useState<string>(() => enemy?.properties?.mp || '');
  const [attack, setAttack] = useState<string>(() => enemy?.properties?.attack || '');
  const [defense, setDefense] = useState<string>(() => enemy?.properties?.defense || '');
  const [speed, setSpeed] = useState<string>(() => enemy?.properties?.speed || '');
  const [xp, setXp] = useState<string>(() => enemy?.properties?.xp || '');
  const [gold, setGold] = useState<string>(() => enemy?.properties?.gold || '');
  const [meleeRange, setMeleeRange] = useState<string>(() => enemy?.properties?.melee_range || '');
  const [threadRange, setThreadRange] = useState<string>(() => enemy?.properties?.thread_range || '');

  // Advanced
  const [statPerLevel, setStatPerLevel] = useState<string>(() => enemy?.properties?.stat_per_level || '');
  const [xpScaling, setXpScaling] = useState<string>(() => enemy?.properties?.xp_scaling || '');
  const [vulnerable, setVulnerable] = useState<string>(() => enemy?.properties?.vulnerable || '');
  // More advanced stats (resists, regen, utility)
  const [resistDamageOverTime, setResistDamageOverTime] = useState<string>(() => enemy?.properties?.resist_damage_over_time || '');
  const [resistSlow, setResistSlow] = useState<string>(() => enemy?.properties?.resist_slow || '');
  const [resistStun, setResistStun] = useState<string>(() => enemy?.properties?.resist_stun || '');
  const [resistKnockback, setResistKnockback] = useState<string>(() => enemy?.properties?.resist_knockback || '');
  const [resistStatDebuff, setResistStatDebuff] = useState<string>(() => enemy?.properties?.resist_stat_debuff || '');
  const [resistDamageReflect, setResistDamageReflect] = useState<string>(() => enemy?.properties?.resist_damage_reflect || '');
  const [xpGain, setXpGain] = useState<string>(() => enemy?.properties?.xp_gain || '');
  const [hpRegen, setHpRegen] = useState<string>(() => enemy?.properties?.hp_regen || '');
  const [mpRegen, setMpRegen] = useState<string>(() => enemy?.properties?.mp_regen || '');
  const [hpSteal, setHpSteal] = useState<string>(() => enemy?.properties?.hp_steal || '');
  const [mpSteal, setMpSteal] = useState<string>(() => enemy?.properties?.mp_steal || '');
  const [accuracy, setAccuracy] = useState<string>(() => enemy?.properties?.accuracy || '');
  const [avoidance, setAvoidance] = useState<string>(() => enemy?.properties?.avoidance || '');
  const [crit, setCrit] = useState<string>(() => enemy?.properties?.crit || '');
  const [absorbMin, setAbsorbMin] = useState<string>(() => enemy?.properties?.absorb_min || '');
  const [absorbMax, setAbsorbMax] = useState<string>(() => enemy?.properties?.absorb_max || '');
  const [poise, setPoise] = useState<string>(() => enemy?.properties?.poise || '');
  const [reflectChance, setReflectChance] = useState<string>(() => enemy?.properties?.reflect_chance || '');
  const [returnDamage, setReturnDamage] = useState<string>(() => enemy?.properties?.return_damage || '');
  const [currencyFind, setCurrencyFind] = useState<string>(() => enemy?.properties?.currency_find || '');
  const [itemFind, setItemFind] = useState<string>(() => enemy?.properties?.item_find || '');
  const [stealth, setStealth] = useState<string>(() => enemy?.properties?.stealth || '');

  // Combat & powers (dmg stats)
  const [dmgMeleeMin, setDmgMeleeMin] = useState<string>(() => enemy?.properties?.dmg_melee_min || '');
  const [dmgMeleeMax, setDmgMeleeMax] = useState<string>(() => enemy?.properties?.dmg_melee_max || '');
  const [dmgRangedMin, setDmgRangedMin] = useState<string>(() => enemy?.properties?.dmg_ranged_min || '');
  const [dmgRangedMax, setDmgRangedMax] = useState<string>(() => enemy?.properties?.dmg_ranged_max || '');
  const [animations, setAnimations] = useState<string>(() => enemy?.properties?.animations || '');

  const [powers, setPowers] = useState<Array<{ state: string; id: string; chance: number }>>(() => {
    try {
      const p = enemy?.properties?.powers;
      if (!p) return [];
      // If it's a string from old version, try to parse it or keep as is?
      // For Flare, powers can be multiple lines. In our MapObject properties, 
      // we might have stored it as JSON or a raw string.
      return JSON.parse(p);
    } catch {
      return [];
    }
  });
  const [script, setScript] = useState<string>(() => enemy?.properties?.script || '');

  // Loot
  const [lootTable, setLootTable] = useState<string>(() => enemy?.properties?.loot || '');
  const [dropChance, setDropChance] = useState<string>(() => enemy?.properties?.drop_chance || '');

  // Behavior flags
  const [isMelee, setIsMelee] = useState<boolean>(() => (enemy?.properties?.melee === 'true'));
  const [isRanged, setIsRanged] = useState<boolean>(() => (enemy?.properties?.ranged === 'true'));
  const [isCaster, setIsCaster] = useState<boolean>(() => (enemy?.properties?.caster === 'true'));
  const [isSummoner, setIsSummoner] = useState<boolean>(() => (enemy?.properties?.summoner === 'true'));
  const [isBoss, setIsBoss] = useState<boolean>(() => (enemy?.properties?.boss === 'true'));
  const [isPassive, setIsPassive] = useState<boolean>(() => (enemy?.properties?.passive === 'true'));
  const [isStationary, setIsStationary] = useState<boolean>(() => (enemy?.properties?.stationary === 'true'));

  // Movement & AI
  const [combatStyle, setCombatStyle] = useState<'default'|'aggressive'|'passive'>(() => ((enemy?.properties?.combat_style as 'default'|'aggressive'|'passive') || 'default'));
  const [threatRange, setThreatRange] = useState<string>(() => enemy?.properties?.threat_range || '');
  const [fleeRange, setFleeRange] = useState<string>(() => enemy?.properties?.flee_range || '');
  const [fleeDuration, setFleeDuration] = useState<string>(() => enemy?.properties?.flee_duration || '');
  const [fleeCooldown, setFleeCooldown] = useState<string>(() => enemy?.properties?.flee_cooldown || '');
  const [chancePursue, setChancePursue] = useState<string>(() => enemy?.properties?.chance_pursue || '');
  const [chanceFlee, setChanceFlee] = useState<string>(() => enemy?.properties?.chance_flee || '');
  const [turnDelay, setTurnDelay] = useState<string>(() => enemy?.properties?.turn_delay || '');
  const [wanderRadius, setWanderRadius] = useState<string>(() => enemy?.properties?.wander_radius || '');
  const [waypoints, setWaypoints] = useState<string>(() => enemy?.properties?.waypoints || '');
  const [waypointPause, setWaypointPause] = useState<string>(() => enemy?.properties?.waypoint_pause || '');
  const [isFacing, setIsFacing] = useState<boolean>(() => (enemy?.properties?.facing === 'true'));
  const [isFlying, setIsFlying] = useState<boolean>(() => (enemy?.properties?.flying === 'true'));
  const [isIntangible, setIsIntangible] = useState<boolean>(() => (enemy?.properties?.intangible === 'true'));

  // Attack & Skills
  const [powersList, setPowersList] = useState<string>(() => enemy?.properties?.powers || '');
  const [passivePowers, setPassivePowers] = useState<string>(() => enemy?.properties?.passive_powers || '');
  const [cooldown, setCooldown] = useState<string>(() => enemy?.properties?.cooldown || '');
  const [cooldownHit, setCooldownHit] = useState<string>(() => enemy?.properties?.cooldown_hit || '');
  const [powerFilter, setPowerFilter] = useState<string>(() => enemy?.properties?.power_filter || '');

  // Actions / Abilities
  const [abilitiesList, setAbilitiesList] = useState<Array<{ id: string; name: string; type: string }>>(() => {
    try {
      const abs = enemy?.properties?.abilities;
      return abs ? JSON.parse(abs) : [];
    } catch {
      return [];
    }
  });

  // Loot
  const [loot, setLoot] = useState<string>(() => enemy?.properties?.loot || '');
  const [lootCount, setLootCount] = useState<string>(() => enemy?.properties?.loot_count || '');
  const [firstDefeatLoot, setFirstDefeatLoot] = useState<string>(() => enemy?.properties?.first_defeat_loot || '');

  // Quest
  const [questLoot, setQuestLoot] = useState<string>(() => enemy?.properties?.quest_loot || '');
  const [defeatStatus, setDefeatStatus] = useState<string>(() => enemy?.properties?.defeat_status || '');

  // Flags / custom
  const [customPropsRaw, setCustomPropsRaw] = useState<string>(() => {
    if (!enemy?.properties) return '';
    const pairs = Object.entries(enemy.properties).filter(([k]) => ![
      'tilesetPath','portraitPath','gfx','render_layers','animation_slots','suppress_hp','hp','mp','attack','defense','speed','xp','gold',
      'melee','ranged','caster','summoner','boss','passive','stationary','humanoid','lifeform',
      'powers','passive_powers','cooldown','cooldown_hit','power_filter','script','loot','loot_count','first_defeat_loot','quest_loot','defeat_status','categories','include'
    ].includes(k));
    return pairs.map(([k,v]) => `${k}=${v}`).join('\n');
  });

  useEffect(() => {
    if (!open) return;
    const t = setTimeout(() => {
      setName(enemy?.name || '');
      setLevel(enemy?.level ?? 1);
      setRarity((enemy?.properties?.rarity as 'common'|'uncommon'|'rare'|'unique') || 'common');
      setCount(enemy?.number ?? 1);

      setCategory(enemy?.category || '');
      setIsHumanoid(enemy?.properties?.humanoid === 'true');
      setIsLifeform(enemy?.properties?.lifeform === 'false' ? false : true);
      setInclude(enemy?.properties?.include || '');

      setTilesetPath((enemy?.properties?.tilesetPath as string) || '');
      setPortraitPath((enemy?.properties?.portraitPath as string) || '');
      setGfx((enemy?.properties?.gfx as string) || '');
      setRenderLayers(enemy?.properties?.render_layers || '');
      setAnimationSlots(enemy?.properties?.animation_slots || '');
      setSuppressHp(enemy?.properties?.suppress_hp === 'true');

      setSfxAttack(enemy?.properties?.sfx_attack || '');
      setSfxHit(enemy?.properties?.sfx_hit || '');
      setSfxDie(enemy?.properties?.sfx_die || '');
      setSfxCritDie(enemy?.properties?.sfx_critdie || '');

      setHp(enemy?.properties?.hp || '');
      setMp(enemy?.properties?.mp || '');
      setAttack(enemy?.properties?.attack || '');
      setDefense(enemy?.properties?.defense || '');
      setSpeed(enemy?.properties?.speed || '');
      setXp(enemy?.properties?.xp || '');
      setGold(enemy?.properties?.gold || '');
      setMeleeRange(enemy?.properties?.melee_range || '');
      setThreadRange(enemy?.properties?.thread_range || '');

      setStatPerLevel(enemy?.properties?.stat_per_level || '');
      setXpScaling(enemy?.properties?.xp_scaling || '');
      setVulnerable(enemy?.properties?.vulnerable || '');

      setIsMelee(enemy?.properties?.melee === 'true');
      setIsRanged(enemy?.properties?.ranged === 'true');
      setIsCaster(enemy?.properties?.caster === 'true');
      setIsSummoner(enemy?.properties?.summoner === 'true');
      setIsBoss(enemy?.properties?.boss === 'true');
      setIsPassive(enemy?.properties?.passive === 'true');
      setIsStationary(enemy?.properties?.stationary === 'true');

      setCombatStyle((enemy?.properties?.combat_style as 'default'|'aggressive'|'passive') || 'default');
      setThreatRange(enemy?.properties?.threat_range || '');
      setFleeRange(enemy?.properties?.flee_range || '');
      setFleeDuration(enemy?.properties?.flee_duration || '');
      setFleeCooldown(enemy?.properties?.flee_cooldown || '');
      setChancePursue(enemy?.properties?.chance_pursue || '');
      setChanceFlee(enemy?.properties?.chance_flee || '');
      setTurnDelay(enemy?.properties?.turn_delay || '');
      setWanderRadius(enemy?.properties?.wander_radius || '');

      try {
        const abs = enemy?.properties?.abilities;
        setAbilitiesList(abs ? JSON.parse(abs) : []);
      } catch {
        setAbilitiesList([]);
      }
      setWaypoints(enemy?.properties?.waypoints || '');
      setWaypointPause(enemy?.properties?.waypoint_pause || '');
      setIsFacing(enemy?.properties?.facing === 'true');
      setIsFlying(enemy?.properties?.flying === 'true');
      setIsIntangible(enemy?.properties?.intangible === 'true');

      setDmgMeleeMin(enemy?.properties?.dmg_melee_min || '');
      setDmgMeleeMax(enemy?.properties?.dmg_melee_max || '');
      setDmgRangedMin(enemy?.properties?.dmg_ranged_min || '');
      setDmgRangedMax(enemy?.properties?.dmg_ranged_max || '');
      setAnimations(enemy?.properties?.animations || '');

      try {
        const p = enemy?.properties?.powers;
        setPowers(p ? JSON.parse(p) : []);
      } catch {
        setPowers([]);
      }

      setPassivePowers(enemy?.properties?.passive_powers || '');
      setCooldown(enemy?.properties?.cooldown || '');
      setCooldownHit(enemy?.properties?.cooldown_hit || '');
      setPowerFilter(enemy?.properties?.power_filter || '');

      setLoot(enemy?.properties?.loot || '');
      setLootCount(enemy?.properties?.loot_count || '');
      setFirstDefeatLoot(enemy?.properties?.first_defeat_loot || '');

      setQuestLoot(enemy?.properties?.quest_loot || '');
      setDefeatStatus(enemy?.properties?.defeat_status || '');

      setCustomPropsRaw(() => {
        if (!enemy?.properties) return '';
        const pairs = Object.entries(enemy.properties).filter(([k]) => !['tilesetPath','portraitPath','gfx','render_layers','animation_slots','suppress_hp','hp','mp','attack','defense','speed','xp','gold','melee','ranged','caster','summoner','boss','passive','stationary','humanoid','lifeform','powers','passive_powers','cooldown','cooldown_hit','power_filter','script','loot','loot_count','first_defeat_loot','quest_loot','defeat_status','categories','combat_style','threat_range','flee_range','flee_duration','flee_cooldown','chance_pursue','chance_flee','turn_delay','wander_radius','waypoints','waypoint_pause','facing','flying','intangible','include'].includes(k));
        return pairs.map(([k,v]) => `${k}=${v}`).join('\n');
      });

      setCategory(enemy?.category || '');
      setInclude(enemy?.properties?.include || '');

    }, 0);

    return () => clearTimeout(t);
  }, [open, enemy]);

  const handleClose = () => onOpenChange ? onOpenChange(false) : undefined;

  const handleSave = () => {
    if (!enemy) {
      handleClose();
      return;
    }

    const newProps: Record<string, string> = { ...(enemy.properties || {}) };
    const knownKeys = [
      'tilesetPath','portraitPath','gfx','render_layers','animation_slots','suppress_hp','hp','mp','attack','defense','speed','xp','gold',
      'melee','ranged','caster','summoner','boss','passive','stationary','humanoid','lifeform',
      'powers','passive_powers','cooldown','cooldown_hit','power_filter','script','loot','loot_count','first_defeat_loot','quest_loot','defeat_status','categories','sfx_attack','sfx_hit','sfx_die','sfx_critdie','melee_range','thread_range','combat_style','threat_range','flee_range','flee_duration','flee_cooldown','chance_pursue','chance_flee','turn_delay','wander_radius','waypoints','flying','intangible','include','abilities'
    ];

    if (rarity) newProps.rarity = rarity; else delete newProps.rarity;
    if (include) newProps.include = include; else delete newProps.include;

    if (tilesetPath) newProps.tilesetPath = tilesetPath; else delete newProps.tilesetPath;
    if (portraitPath) newProps.portraitPath = portraitPath; else delete newProps.portraitPath;
    if (gfx) newProps.gfx = gfx; else delete newProps.gfx;
    if (renderLayers) newProps.render_layers = renderLayers; else delete newProps.render_layers;
    if (animationSlots) newProps.animation_slots = animationSlots; else delete newProps.animation_slots;
    if (suppressHp) newProps.suppress_hp = 'true'; else delete newProps.suppress_hp;

    if (sfxAttack) newProps.sfx_attack = sfxAttack; else delete newProps.sfx_attack;
    if (sfxHit) newProps.sfx_hit = sfxHit; else delete newProps.sfx_hit;
    if (sfxDie) newProps.sfx_die = sfxDie; else delete newProps.sfx_die;
    if (sfxCritDie) newProps.sfx_critdie = sfxCritDie; else delete newProps.sfx_critdie;

    if (hp) newProps.hp = hp; else delete newProps.hp;
    if (mp) newProps.mp = mp; else delete newProps.mp;
    if (attack) newProps.attack = attack; else delete newProps.attack;
    if (defense) newProps.defense = defense; else delete newProps.defense;
    if (speed) newProps.speed = speed; else delete newProps.speed;
    if (xp) newProps.xp = xp; else delete newProps.xp;
    if (gold) newProps.gold = gold; else delete newProps.gold;

    if (statPerLevel) newProps.stat_per_level = statPerLevel; else delete newProps.stat_per_level;
    if (xpScaling) newProps.xp_scaling = xpScaling; else delete newProps.xp_scaling;
    if (vulnerable) newProps.vulnerable = vulnerable; else delete newProps.vulnerable;

    if (meleeRange) newProps.melee_range = meleeRange; else delete newProps.melee_range;
    if (threadRange) newProps.thread_range = threadRange; else delete newProps.thread_range;

    if (isMelee) newProps.melee = 'true'; else delete newProps.melee;
    if (isRanged) newProps.ranged = 'true'; else delete newProps.ranged;
    if (isCaster) newProps.caster = 'true'; else delete newProps.caster;
    if (isSummoner) newProps.summoner = 'true'; else delete newProps.summoner;
    if (isBoss) newProps.boss = 'true'; else delete newProps.boss;
    if (isPassive) newProps.passive = 'true'; else delete newProps.passive;
    if (isStationary) newProps.stationary = 'true'; else delete newProps.stationary;
    if (isHumanoid) newProps.humanoid = 'true'; else delete newProps.humanoid;
    if (isLifeform) newProps.lifeform = 'true'; else delete newProps.lifeform;

    if (combatStyle) newProps.combat_style = combatStyle; else delete newProps.combat_style;
    if (threatRange) newProps.threat_range = threatRange; else delete newProps.threat_range;
    if (fleeRange) newProps.flee_range = fleeRange; else delete newProps.flee_range;
    if (fleeDuration) newProps.flee_duration = fleeDuration; else delete newProps.flee_duration;
    if (fleeCooldown) newProps.flee_cooldown = fleeCooldown; else delete newProps.flee_cooldown;
    if (chancePursue) newProps.chance_pursue = chancePursue; else delete newProps.chance_pursue;
    if (chanceFlee) newProps.chance_flee = chanceFlee; else delete newProps.chance_flee;
    if (turnDelay) newProps.turn_delay = turnDelay; else delete newProps.turn_delay;
    if (wanderRadius) newProps.wander_radius = wanderRadius; else delete newProps.wander_radius;
    if (waypoints) newProps.waypoints = waypoints; else delete newProps.waypoints;
    if (waypointPause) newProps.waypoint_pause = waypointPause; else delete newProps.waypoint_pause;
    if (isFacing) newProps.facing = 'true'; else delete newProps.facing;
    if (isFlying) newProps.flying = 'true'; else delete newProps.flying;
    if (isIntangible) newProps.intangible = 'true'; else delete newProps.intangible;

    if (dmgMeleeMin) newProps.dmg_melee_min = dmgMeleeMin; else delete newProps.dmg_melee_min;
    if (dmgMeleeMax) newProps.dmg_melee_max = dmgMeleeMax; else delete newProps.dmg_melee_max;
    if (dmgRangedMin) newProps.dmg_ranged_min = dmgRangedMin; else delete newProps.dmg_ranged_min;
    if (dmgRangedMax) newProps.dmg_ranged_max = dmgRangedMax; else delete newProps.dmg_ranged_max;
    if (animations) newProps.animations = animations; else delete newProps.animations;

    if (powersList) {
      newProps.powers = powersList;
    } else if (powers && powers.length > 0) {
      newProps.powers = JSON.stringify(powers);
    } else {
      delete newProps.powers;
    }
    if (passivePowers) newProps.passive_powers = passivePowers; else delete newProps.passive_powers;
    if (cooldown) newProps.cooldown = cooldown; else delete newProps.cooldown;
    if (cooldownHit) newProps.cooldown_hit = cooldownHit; else delete newProps.cooldown_hit;
    if (powerFilter) newProps.power_filter = powerFilter; else delete newProps.power_filter;

    if (loot) newProps.loot = loot; else delete newProps.loot;
    if (lootCount) newProps.loot_count = lootCount; else delete newProps.loot_count;
    if (firstDefeatLoot) newProps.first_defeat_loot = firstDefeatLoot; else delete newProps.first_defeat_loot;

    if (questLoot) newProps.quest_loot = questLoot; else delete newProps.quest_loot;
    if (defeatStatus) newProps.defeat_status = defeatStatus; else delete newProps.defeat_status;
    if (abilitiesList.length > 0) newProps.abilities = JSON.stringify(abilitiesList); else delete newProps.abilities;

    const customLines = (customPropsRaw || '').split(/\r?\n/).map(l => l.trim()).filter(Boolean);
    for (const k of Object.keys(newProps)) {
      if (!knownKeys.includes(k)) delete newProps[k];
    }
    for (const line of customLines) {
      const eq = line.indexOf('=');
      if (eq > 0) {
        const k = line.slice(0, eq).trim();
        const v = line.slice(eq + 1).trim();
        if (k) newProps[k] = v;
      }
    }

    const updated: MapObject = {
      ...enemy,
      name,
      level: Number.isFinite(Number(level)) ? Number(level) : enemy.level,
      number: Number.isFinite(Number(count)) ? Number(count) : enemy.number,
      category: category,
      properties: newProps,
    };

    onSave?.(updated);
    handleClose();
  };

  const handleCloseDecision = (decision: 'save' | 'discard' | 'cancel') => {
    if (decision === 'save') {
      handleSave();
    }
    onCloseDecision?.(decision);
  };

  const combatStyles: Array<{ id: 'default' | 'aggressive' | 'passive'; label: string }> = [
    { id: 'default', label: 'Default' },
    { id: 'aggressive', label: 'Aggressive' },
    { id: 'passive', label: 'Passive' },
  ];

  if (!open && !inline) return null;

  const CollapsibleSection = ({ title, icon: Icon, isExpanded, onToggle, children, id }: { title: string; icon: LucideIcon; isExpanded: boolean; onToggle: () => void; children: React.ReactNode; id: string }) => (
    <div className="border border-border/50 rounded-lg overflow-hidden mb-4 shadow-sm" id={`section-${id}`}>
      <button
        type="button"
        onClick={onToggle}
        className="w-full flex items-center justify-between p-3 bg-muted/20 hover:bg-muted/30 transition-colors select-none"
      >
        <div className="flex items-center gap-2">
          <Icon className="w-4 h-4 text-orange-500" />
          <span className="text-sm font-semibold tracking-wide">{title}</span>
        </div>
        {isExpanded ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}
      </button>
      {isExpanded && <div className="p-4 bg-background border-t border-border/10 animate-in slide-in-from-top-2 duration-200">{children}</div>}
    </div>
  );

  const panel = (
    <div className="flex-1 flex flex-col overflow-hidden relative">
      <div className="flex-1 overflow-y-auto p-6 min-h-0 custom-scrollbar">
        <CollapsibleSection title="Identity" icon={User} id="identity" isExpanded={expandedSections.identity} onToggle={() => toggleSection('identity')}>
              <div className="grid grid-cols-2 gap-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
                <div className="space-y-4">
                  <div>
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-1.5 block">Name & Identifiers</label>
                    <div className="space-y-3">
                      <div className="space-y-1">
                        <label className="text-xs text-muted-foreground">Full Name</label>
                        <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Goblin Warrior" className="h-9" />
                      </div>
                      <div className="grid grid-cols-2 gap-3">
                        <div className="space-y-1">
                          <label className="text-xs text-muted-foreground">Level</label>
                          <Input type="number" value={level} onChange={(e) => setLevel(Number(e.target.value))} className="h-9" />
                        </div>
                        <div className="space-y-1">
                          <label className="text-xs text-muted-foreground">Spawn Number</label>
                          <Input type="number" value={count} onChange={(e) => setCount(Number(e.target.value))} className="h-9" />
                        </div>
                      </div>
                    </div>
                  </div>

                  <div>
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-1.5 block">Categories</label>
                    <div className="p-3 border border-border/50 rounded-lg bg-muted/20">
                      <div className="flex flex-wrap gap-1.5 mb-3">
                        {selectedCategories.map((cat) => (
                          <Badge key={cat} variant="secondary" className="pl-2 pr-1 h-6 gap-1 bg-background border-border/50">
                            {cat}
                            <button onClick={() => toggleCategory(cat)} className="hover:text-red-500 transition-colors">
                              <X className="w-3 h-3" />
                            </button>
                          </Badge>
                        ))}
                        {selectedCategories.length === 0 && <span className="text-[11px] text-muted-foreground italic">No categories...</span>}
                      </div>
                      
                      {isAddingCategory ? (
                        <div className="flex gap-1.5">
                          <Input 
                            autoFocus 
                            value={newCatInput} 
                            onChange={(e) => setNewCatInput(e.target.value)}
                            onKeyDown={(e) => e.key === 'Enter' && addCategory()} 
                            placeholder="cat name..." 
                            className="h-7 text-xs" 
                          />
                          <Button size="sm" onClick={addCategory} className="h-7 px-2">Add</Button>
                          <Button size="sm" variant="ghost" onClick={() => setIsAddingCategory(false)} className="h-7 px-2"><X className="w-3 h-3" /></Button>
                        </div>
                      ) : (
                        <Button 
                          variant="outline" 
                          size="sm" 
                          onClick={() => setIsAddingCategory(true)}
                          className="w-full h-7 text-[10px] border-dashed"
                        >
                          <Plus className="w-3 h-3 mr-1" /> Add Category
                        </Button>
                      )}
                    </div>
                  </div>
                </div>

                <div className="space-y-4">
                   <div>
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-1.5 block">File & Inheritance</label>
                    <div className="space-y-3">
                      <div className="space-y-1">
                        <label className="text-xs text-muted-foreground flex items-center gap-1">
                          Include Base
                          <Tooltip content="Path to another enemy file to inherit properties from. e.g. enemies/base/goblin.txt">
                            <HelpCircle className="w-3 h-3" />
                          </Tooltip>
                        </label>
                        <Input value={include} onChange={(e) => setInclude(e.target.value)} placeholder="enemies/base/..." className="h-9 font-mono text-xs" />
                      </div>
                      <div className="space-y-1">
                        <label className="text-xs text-muted-foreground">Rarity</label>
                        <Select value={rarity} onValueChange={(v: any) => setRarity(v)}>
                          <SelectTrigger className="h-9">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="common">Common</SelectItem>
                            <SelectItem value="uncommon">Uncommon</SelectItem>
                            <SelectItem value="rare">Rare</SelectItem>
                            <SelectItem value="unique">Unique</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-2 pt-2">
                    <label className="flex items-center gap-2 cursor-pointer group">
                      <input type="checkbox" checked={isHumanoid} onChange={(e) => setIsHumanoid(e.target.checked)} className="h-4 w-4 rounded border-border" />
                      <span className="text-sm">Humanoid</span>
                    </label>
                    <label className="flex items-center gap-2 cursor-pointer group">
                      <input type="checkbox" checked={isLifeform} onChange={(e) => setIsLifeform(e.target.checked)} className="h-4 w-4 rounded border-border" />
                      <span className="text-sm">Lifeform</span>
                    </label>
                  </div>
                </div>
              </div>
        </CollapsibleSection>

        <CollapsibleSection title="Visual & Animations" icon={Eye} id="visual" isExpanded={expandedSections.visual} onToggle={() => toggleSection('visual')}>
              <div className="grid grid-cols-2 gap-6 animate-in fade-in zoom-in-95 duration-300">
                <div className="space-y-4">
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">GFX (Animation Template)</label>
                    <Input value={gfx} onChange={(e) => setGfx(e.target.value)} placeholder="e.g. gob_war" className="h-9" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Animations Definition File</label>
                    <Input value={animations} onChange={(e) => setAnimations(e.target.value)} placeholder="animations/enemies/goblin.txt" className="h-9 font-mono text-xs" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Tileset Source (Internal)</label>
                    <div className="flex gap-2">
                      <Input value={tilesetPath} onChange={(e) => setTilesetPath(e.target.value)} className="h-9 text-xs flex-1" />
                    </div>
                  </div>
                </div>
                <div className="space-y-4">
                   <div className="space-y-1">
                    <label className="text-xs font-semibold">Render Layers</label>
                    <Input value={renderLayers} onChange={(e) => setRenderLayers(e.target.value)} placeholder="e.g. floor,object" className="h-9" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Animation Slots</label>
                    <Input value={animationSlots} onChange={(e) => setAnimationSlots(e.target.value)} placeholder="e.g. body,weapon" className="h-9" />
                  </div>
                  <div className="p-4 border border-border/50 rounded-lg bg-muted/10 flex flex-col items-center justify-center min-h-[140px]">
                     {portraitPath ? (
                        <img src={portraitPath} alt="Portrait" className="w-24 h-24 object-contain rounded-md shadow-inner border border-border" />
                      ) : (
                        <div className="text-muted-foreground text-xs text-center">
                          <Eye className="w-8 h-8 mx-auto mb-2 opacity-20" />
                          No Portrait
                        </div>
                      )}
                    </div>
                  </div>
                </div>
        </CollapsibleSection>

        <CollapsibleSection title="SFX & Audio" icon={Volume2} id="audio" isExpanded={expandedSections.audio} onToggle={() => toggleSection('audio')}>
              <div className="space-y-4 animate-in fade-in slide-in-from-left-4 duration-300">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Attack SFX</label>
                    <Input value={sfxAttack} onChange={(e) => setSfxAttack(e.target.value)} placeholder="soundfx/enemies/hit.ogg" className="h-9 text-xs" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Hit SFX</label>
                    <Input value={sfxHit} onChange={(e) => setSfxHit(e.target.value)} placeholder="soundfx/enemies/pain.ogg" className="h-9 text-xs" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Death SFX</label>
                    <Input value={sfxDie} onChange={(e) => setSfxDie(e.target.value)} placeholder="soundfx/enemies/die.ogg" className="h-9 text-xs" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Crit Death SFX</label>
                    <Input value={sfxCritDie} onChange={(e) => setSfxCritDie(e.target.value)} placeholder="soundfx/enemies/crit.ogg" className="h-9 text-xs" />
                  </div>
                </div>
              </div>
        </CollapsibleSection>

        <CollapsibleSection title="Core Stats" icon={Sigma} id="stats" isExpanded={expandedSections.stats} onToggle={() => toggleSection('stats')}>
              <div className="space-y-6 animate-in fade-in duration-300">
                <div className="grid grid-cols-3 gap-4">
                  <div className="p-3 border rounded-lg bg-muted/10">
                    <label className="text-[10px] font-bold uppercase text-red-500 mb-1 block">Health</label>
                    <Input type="number" value={hp} onChange={(e) => setHp(e.target.value)} className="h-8 text-center font-bold" />
                  </div>
                  <div className="p-3 border rounded-lg bg-muted/10">
                    <label className="text-[10px] font-bold uppercase text-blue-500 mb-1 block">Mana</label>
                    <Input type="number" value={mp} onChange={(e) => setMp(e.target.value)} className="h-8 text-center" />
                  </div>
                  <div className="p-3 border rounded-lg bg-muted/10">
                    <label className="text-[10px] font-bold uppercase text-green-500 mb-1 block">Speed</label>
                    <Input type="number" value={speed} onChange={(e) => setSpeed(e.target.value)} className="h-8 text-center" step="0.1" />
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-4">
                   <div className="space-y-1">
                    <label className="text-xs font-semibold">Accuracy</label>
                    <Input type="number" value={accuracy} onChange={(e) => setAccuracy(e.target.value)} className="h-8" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Avoidance</label>
                    <Input type="number" value={avoidance} onChange={(e) => setAvoidance(e.target.value)} className="h-8" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Crit Rate</label>
                    <Input type="number" value={crit} onChange={(e) => setCrit(e.target.value)} className="h-8" />
                  </div>
                   <div className="space-y-1">
                    <label className="text-xs font-semibold">Poise</label>
                    <Input type="number" value={poise} onChange={(e) => setPoise(e.target.value)} className="h-8" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Absorb Min</label>
                    <Input type="number" value={absorbMin} onChange={(e) => setAbsorbMin(e.target.value)} className="h-8" />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-semibold">Absorb Max</label>
                    <Input type="number" value={absorbMax} onChange={(e) => setAbsorbMax(e.target.value)} className="h-8" />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4 border-t pt-4">
                   <div className="space-y-1">
                    <label className="text-xs font-semibold">Stealth</label>
                    <Input type="number" value={stealth} onChange={(e) => setStealth(e.target.value)} className="h-8" />
                  </div>
                   <div className="space-y-1">
                    <label className="text-xs font-semibold">Reflect Chance %</label>
                    <Input type="number" value={reflectChance} onChange={(e) => setReflectChance(e.target.value)} className="h-8" />
                  </div>
                </div>
              </div>
        </CollapsibleSection>

        <CollapsibleSection title="Combat & Damage" icon={Sword} id="combat" isExpanded={expandedSections.combat} onToggle={() => toggleSection('combat')}>
              <div className="space-y-6 animate-in fade-in duration-300">
                <div className="space-y-4">
                  <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">Melee Damage</label>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="space-y-1">
                      <label className="text-xs text-muted-foreground">Min</label>
                      <Input type="number" value={dmgMeleeMin} onChange={(e) => setDmgMeleeMin(e.target.value)} className="h-9" />
                    </div>
                    <div className="space-y-1">
                      <label className="text-xs text-muted-foreground">Max</label>
                      <Input type="number" value={dmgMeleeMax} onChange={(e) => setDmgMeleeMax(e.target.value)} className="h-9" />
                    </div>
                    <div className="space-y-1">
                      <label className="text-xs text-muted-foreground">Range</label>
                      <Input type="number" value={meleeRange} onChange={(e) => setMeleeRange(e.target.value)} step="0.1" className="h-9" />
                    </div>
                  </div>
                </div>

                <div className="space-y-4 border-t pt-4">
                  <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">Ranged Damage</label>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1">
                      <label className="text-xs text-muted-foreground">Min</label>
                      <Input type="number" value={dmgRangedMin} onChange={(e) => setDmgRangedMin(e.target.value)} className="h-9" />
                    </div>
                    <div className="space-y-1">
                      <label className="text-xs text-muted-foreground">Max</label>
                      <Input type="number" value={dmgRangedMax} onChange={(e) => setDmgRangedMax(e.target.value)} className="h-9" />
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4 border-t pt-4">
                    <div className="space-y-1">
                      <label className="text-xs font-semibold">Global Cooldown</label>
                      <Input value={cooldown} onChange={(e) => setCooldown(e.target.value)} placeholder="e.g. 1500ms" className="h-9" />
                    </div>
                    <div className="space-y-1">
                      <label className="text-xs font-semibold">Cooldown on Hit</label>
                      <Input value={cooldownHit} onChange={(e) => setCooldownHit(e.target.value)} placeholder="e.g. 500ms" className="h-9" />
                    </div>
                </div>
              </div>
        </CollapsibleSection>

        <CollapsibleSection title="Powers" icon={Zap} id="powers" isExpanded={expandedSections.skills} onToggle={() => toggleSection('skills')}>
              <div className="space-y-4 animate-in fade-in duration-300">
                <div className="space-y-3">
                  <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Powers</label>
                  <Input
                    value={powersList}
                    onChange={(e) => setPowersList(e.target.value)}
                    placeholder="e.g. fireball, ice_shard, summon_wolf"
                    className="h-9 text-xs"
                  />
                  <p className="text-xs text-muted-foreground">Simple power list for now; a full power layer will come later.</p>
                </div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Active Powers</label>
                  <Button size="sm" variant="outline" onClick={() => setPowers(prev => [...prev, { state: 'melee', id: '', chance: 100 }])} className="h-7 text-[10px]">
                    <Plus className="w-3 h-3 mr-1" /> Add Power
                  </Button>
                </div>

                <div className="space-y-2 max-h-[300px] overflow-y-auto pr-2 custom-scrollbar">
                  {powers.map((pow, index) => (
                    <div key={index} className="flex items-center gap-2 p-3 bg-muted/30 border border-border/50 rounded-lg group">
                      <div className="w-24">
                        <Select value={pow.state} onValueChange={(v) => {
                          const newP = [...powers];
                          newP[index].state = v;
                          setPowers(newP);
                        }}>
                          <SelectTrigger className="h-8 text-[11px]">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="melee">Melee</SelectItem>
                            <SelectItem value="ranged">Ranged</SelectItem>
                            <SelectItem value="beacon">Beacon</SelectItem>
                            <SelectItem value="on_hit">On Hit</SelectItem>
                            <SelectItem value="on_death">On Death</SelectItem>
                            <SelectItem value="on_half_dead">On Half Dead</SelectItem>
                            <SelectItem value="on_join_combat">On Join Combat</SelectItem>
                            <SelectItem value="on_debuff">On Debuff</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      <Input 
                        placeholder="Power ID" 
                        value={pow.id} 
                        onChange={(e) => {
                          const newP = [...powers];
                          newP[index].id = e.target.value;
                          setPowers(newP);
                        }}
                        className="h-8 flex-1 text-xs" 
                      />
                      <div className="w-20 flex items-center gap-1">
                        <Input 
                          type="number" 
                          value={pow.chance} 
                          onChange={(e) => {
                            const newP = [...powers];
                            newP[index].chance = Number(e.target.value);
                            setPowers(newP);
                          }}
                          className="h-8 text-center text-xs" 
                        />
                        <span className="text-[10px]">%</span>
                      </div>
                      <Button 
                        variant="ghost" 
                        size="sm" 
                        onClick={() => setPowers(prev => prev.filter((_, i) => i !== index))}
                        className="h-8 w-8 p-0 text-muted-foreground hover:text-red-500"
                      >
                        <X className="w-4 h-4" />
                      </Button>
                    </div>
                  ))}
                  {powers.length === 0 && (
                    <div className="text-center p-8 border border-dashed rounded-lg text-muted-foreground text-xs">
                      No powers defined. Click &quot;Add Power&quot; above.
                    </div>
                  )}
                </div>

                <div className="border-t pt-4">
                    <label className="text-xs font-semibold mb-1.5 block">Passive Powers (comma-separated IDs)</label>
                    <Input value={passivePowers} onChange={(e) => setPassivePowers(e.target.value)} placeholder="e.g. health_regen,armor_bonus" className="h-9 text-xs" />
                </div>
              </div>
        </CollapsibleSection>

        <CollapsibleSection title="Behavior & AI" icon={Rabbit} id="behavior" isExpanded={expandedSections.behavior} onToggle={() => toggleSection('behavior')}>
              <div className="space-y-6 animate-in fade-in duration-300">
                <div className="grid grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">AI Style</label>
                    <Select value={combatStyle} onValueChange={(v: any) => setCombatStyle(v)}>
                      <SelectTrigger className="h-9">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="default">Default (Standard)</SelectItem>
                        <SelectItem value="aggressive">Aggressive (Always Combat)</SelectItem>
                        <SelectItem value="passive">Passive (Fights Back)</SelectItem>
                      </SelectContent>
                    </Select>
                    <div className="text-[10px] text-muted-foreground bg-muted/20 p-2 rounded border">
                      {combatStyle === 'aggressive' ? 'Always in combat. Ignores threat range.' : combatStyle === 'passive' ? 'Only attacks if hit first.' : 'Engages when player is in range.'}
                    </div>
                  </div>

                  <div className="space-y-4">
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">Ranges</label>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="space-y-1">
                        <label className="text-[10px] text-muted-foreground">Threat (Engage)</label>
                        <Input value={threatRange} onChange={(e) => setThreatRange(e.target.value)} className="h-8" />
                      </div>
                      <div className="space-y-1">
                        <label className="text-[10px] text-muted-foreground">Flee Range</label>
                        <Input value={fleeRange} onChange={(e) => setFleeRange(e.target.value)} className="h-8" />
                      </div>
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-6 border-t pt-4">
                  <div className="space-y-3">
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">Probabilities</label>
                    <div className="space-y-3">
                      <div className="space-y-1">
                        <div className="flex justify-between text-[11px] mb-1">
                           <span>Chance Pursue</span>
                           <span className="font-bold">{chancePursue || 0}%</span>
                        </div>
                        <Slider value={parseInt(chancePursue || '0', 10)} onChange={v => setChancePursue(String(v))} min={0} max={100} step={5} />
                      </div>
                      <div className="space-y-1">
                        <div className="flex justify-between text-[11px] mb-1">
                           <span>Chance Flee</span>
                           <span className="font-bold">{chanceFlee || 0}%</span>
                        </div>
                        <Slider value={parseInt(chanceFlee || '0', 10)} onChange={v => setChanceFlee(String(v))} min={0} max={100} step={5} />
                      </div>
                    </div>
                  </div>

                  <div className="space-y-3">
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">Movement</label>
                    <div className="grid grid-cols-2 gap-3">
                       <div className="space-y-1">
                          <label className="text-[10px] text-muted-foreground">Turn Delay</label>
                          <Input value={turnDelay} onChange={(e) => setTurnDelay(e.target.value)} placeholder="200ms" className="h-8" />
                       </div>
                       <div className="space-y-1">
                          <label className="text-[10px] text-muted-foreground">Wander Radius</label>
                          <Input value={wanderRadius} onChange={(e) => setWanderRadius(e.target.value)} placeholder="0" className="h-8" />
                       </div>
                    </div>
                     <div className="space-y-2 mt-2">
                        <label className="flex items-center gap-2 cursor-pointer">
                          <input type="checkbox" checked={isFacing} onChange={e => setIsFacing(e.target.checked)} className="h-3.5 w-3.5" />
                          <span className="text-xs">Always Face Target</span>
                        </label>
                         <label className="flex items-center gap-2 cursor-pointer">
                          <input type="checkbox" checked={isFlying} onChange={e => setIsFlying(e.target.checked)} className="h-3.5 w-3.5" />
                          <span className="text-xs">Flying (Ignore Chasm)</span>
                        </label>
                         <label className="flex items-center gap-2 cursor-pointer">
                          <input type="checkbox" checked={isIntangible} onChange={e => setIsIntangible(e.target.checked)} className="h-3.5 w-3.5" />
                          <span className="text-xs">Intangible (Through Walls)</span>
                        </label>
                     </div>
                  </div>
                </div>
              </div>
        </CollapsibleSection>

        <CollapsibleSection title="Loot & Rewards" icon={Gift} id="loot" isExpanded={expandedSections.loot} onToggle={() => toggleSection('loot')}>
              <div className="space-y-6 animate-in fade-in duration-300">
                <div className="grid grid-cols-2 gap-6">
                   <div className="space-y-4">
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">Rewards</label>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="space-y-1">
                        <label className="text-[10px] text-muted-foreground">Kill XP</label>
                        <Input type="number" value={xp} onChange={(e) => setXp(e.target.value)} className="h-9" />
                      </div>
                      <div className="space-y-1">
                        <label className="text-[10px] text-muted-foreground">Base Gold</label>
                        <Input type="number" value={gold} onChange={(e) => setGold(e.target.value)} className="h-9" />
                      </div>
                    </div>
                  </div>
                   <div className="space-y-4">
                    <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">Modifiers</label>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="space-y-1">
                        <label className="text-[10px] text-muted-foreground">Item Find %</label>
                        <Input value={itemFind} onChange={(e) => setItemFind(e.target.value)} className="h-9" />
                      </div>
                      <div className="space-y-1">
                        <label className="text-[10px] text-muted-foreground">Currency Find %</label>
                        <Input value={currencyFind} onChange={(e) => setCurrencyFind(e.target.value)} className="h-9" />
                      </div>
                    </div>
                  </div>
                </div>

                <div className="space-y-4 border-t pt-4">
                  <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground block">Loot Tables</label>
                  <div className="space-y-3">
                    <div className="space-y-1">
                      <label className="text-xs text-muted-foreground">Standard Loot</label>
                      <Input value={loot} onChange={(e) => setLoot(e.target.value)} placeholder="loot/level_1.txt" className="h-9 font-mono text-xs" />
                    </div>
                     <div className="grid grid-cols-2 gap-3">
                        <div className="space-y-1">
                          <label className="text-xs text-muted-foreground">Loot Count Range</label>
                          <Input value={lootCount} onChange={(e) => setLootCount(e.target.value)} placeholder="e.g. 1,3" className="h-9" />
                        </div>
                         <div className="space-y-1">
                          <label className="text-xs text-muted-foreground">First Defeat Loot</label>
                          <Input value={firstDefeatLoot} onChange={(e) => setFirstDefeatLoot(e.target.value)} className="h-9 font-mono text-xs" />
                        </div>
                     </div>
                  </div>
                </div>
              </div>
        </CollapsibleSection>

        <CollapsibleSection title="Quest & Status" icon={MapPin} id="quest" isExpanded={expandedSections.quest} onToggle={() => toggleSection('quest')}>
              <div className="space-y-4 animate-in fade-in duration-300">
                <div className="space-y-1">
                  <label className="text-xs font-semibold">Defeat Status</label>
                  <Input value={defeatStatus} onChange={(e) => setDefeatStatus(e.target.value)} placeholder="e.g. boss_defeated" className="h-9 font-mono text-xs" />
                  <p className="text-[10px] text-muted-foreground italic">Campaign status set when this enemy dies.</p>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-semibold">Quest Loot</label>
                  <Input value={questLoot} onChange={(e) => setQuestLoot(e.target.value)} placeholder="16,100 (item_id, chance)" className="h-9 font-mono text-xs" />
                   <p className="text-[10px] text-muted-foreground italic">Item dropped only if a quest requires it.</p>
                </div>
              </div>
        </CollapsibleSection>

        <CollapsibleSection title="Custom Flags" icon={Flag} id="flags" isExpanded={expandedSections.flags} onToggle={() => toggleSection('flags')}>
              <div className="flex flex-col h-full animate-in fade-in duration-300">
                <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-2">Raw Property Editor</label>
                <textarea 
                  value={customPropsRaw} 
                  onChange={(e) => setCustomPropsRaw(e.target.value)} 
                  className="flex-1 min-h-[300px] w-full bg-muted/10 border border-border rounded-lg p-3 font-mono text-xs focus:ring-1 focus:ring-orange-500 outline-none resize-none" 
                  placeholder="KEY=VALUE"
                />
                <p className="text-[10px] text-muted-foreground mt-2">
                  Add any properties not covered by the GUI. These will be appended exactly as written to the enemy file.
                </p>
              </div>
        </CollapsibleSection>
      </div>

      <Button 
        onClick={handleSave} 
        className="absolute bottom-3 right-3 z-[60] bg-orange-500 hover:bg-orange-600 text-white w-9 h-9 p-0 flex items-center justify-center rounded-lg shadow-xl border border-background active:scale-95 transition-all"
        title="Save"
      >
        <Save className="w-4 h-4" />
      </Button>
    </div>
  );

  if (inline) {
    return (
      <div className="w-full h-full p-0 overflow-hidden flex flex-col relative bg-background">
        {panel}
      </div>
    );
  }

  if (!open) return null;

  return createPortal(
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/40" onClick={() => onOpenChange?.(false)}>
      <div 
        ref={dialogRef}
        className="bg-background border border-border/70 rounded-lg flex flex-col shadow-xl"
        style={{
          position: 'fixed',
          left: `${position.x}px`,
          top: `${position.y}px`,
          width: `${size.width}px`,
          height: `${size.height}px`,
          pointerEvents: 'auto',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div 
          className="flex items-center justify-between p-4 border-b border-border cursor-move select-none"
          onMouseDown={handleHeaderMouseDown}
        >
          <div className="flex items-center gap-2">
            <Sword className="w-5 h-5 text-orange-500" />
            {name && <Badge variant="outline" className="bg-muted/30">{name}</Badge>}
          </div>
          <button
            onClick={() => onOpenChange?.(false)}
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="flex-1 overflow-hidden flex flex-col">
          {panel}
        </div>

        {/* Resize handle */}
        <div
          onMouseDown={handleResizeMouseDown}
          className="absolute bottom-0 right-0 w-5 h-5 cursor-se-resize opacity-40 hover:opacity-100 transition-opacity flex items-end justify-end"
          title="Drag to resize"
        >
          <div className="w-1.5 h-1.5 bg-foreground/40 rounded-sm m-1" />
        </div>
      </div>
    </div>,
    document.body
  );
}
